details:
  name: Capstone
  repository_name: unit-capstone
sequence: # even though there is only one group/sequence - This structure is needed for the GitHub copying tool
  Capstone:
    - name: Unit 6 Launch
      elements:
        - kind: deck
        - kind: recording
    - name: Capstone Workbook
      activity: canvas_url
      activity_description: "<p>Go to the slide deck below. One person from each Capstone group should create a copy of the Capstone Workbook. Submit a URL to your group's copied version in this assignment.</p> <br> <a href='https://docs.google.com/presentation/d/1zaHdrvt3e0FjpjSjWh3bEn2bhzAp6U8vGjNjfeaGbHI/edit#slide=id.g6c1b6be0e1_0_0'>Capstone Workbook</a>

      <p>Make sure that everyone in your group has Edit access to the Capstone Workbook before you submit.</p>"
      points_possible: 0
      kind: task # Submission only
    - name: Group Norms
      pursuit_path: group-norms
      kind: lesson
      activity: ~
    - name: Git and GitHub with Teams
      pursuit_path: git-github-w-teams
      kind: lesson # Submission only
      activity: ~
    - name: Ideation
      pursuit_path: ideation
      kind: lesson
      activity: ~
    - name: Capstone Application
      activity: canvas_url
      activity_description: "<p>Submit the URL for your deployed Capstone application.</p>"
      points_possible: 0
      kind: task # Submission only
    - name: Capstone Presentation Deck
      activity: canvas_url
      activity_description: "<p>Once you have created your presentation deck, submit a link to share with your instructional team.</p>"
      points_possible: 0
      kind: task # Submission only
    - name: Capstone Copy Back-end GitHub
      activity: canvas_url
      activity_description: "<p>Submit a link to the <em>personal version</em> of your Capstone back-end's GitHub repository. This link should be to your own GitHub account, not a member of your group's.</p>"
      points_possible: 0
      kind: task # Submission only
    - name: Capstone Copy Front-end GitHub
      activity: canvas_url
      activity_description: "<p>Submit a link to the <em>personal version</em> of your Capstone front-end's GitHub repository. This link should be to your own GitHub account, not a member of your group's.</p>"
      points_possible: 0
      kind: task # Submission only
    - name: Capstone Copy Deployed URL
      activity: canvas_url
      activity_description: "<p>Submit a link to the <em>personal version</em> of your deployed Capstone application. This link should be a deployed application that you manage, not related to a member of your group.</p>"
      points_possible: 0
      kind: task # Submission only